// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai-agent/assign-knowledge-base': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/assign-knowledge-base.post').default>>>>
    }
    '/api/ai-agent/knowledge-base': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/knowledge-base.get').default>>>>
    }
    '/api/ai-agent/knowledge-base/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/knowledge-base/[id].delete').default>>>>
    }
    '/api/ai-agent/summarize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/summarize.post').default>>>>
    }
    '/api/ai-agent/unassign-knowledge-base': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/unassign-knowledge-base.post').default>>>>
    }
    '/api/ai-agent/upload-knowledge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-agent/upload-knowledge.post').default>>>>
    }
    '/api/scrape-property': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scrape-property.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}