// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2025, 1:10:43 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/Nico/Downloads/crm-nuxt-propeo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/plugins/**/*.{js,ts,mjs}","/Users/Nico/Downloads/crm-nuxt-propeo/composables/**/*.{js,ts,mjs}","/Users/Nico/Downloads/crm-nuxt-propeo/utils/**/*.{js,ts,mjs}","/Users/Nico/Downloads/crm-nuxt-propeo/pages/admin.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/admin/index.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/admin/login.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/auth/login.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/auth/register.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/agency.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/ai-agent.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/calendar.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/calls.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/index.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/dashboard/properties.vue","/Users/Nico/Downloads/crm-nuxt-propeo/pages/index.vue","/Users/Nico/Downloads/crm-nuxt-propeo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/Nico/Downloads/crm-nuxt-propeo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;